### ISSUE TITLE
Percentiles

### ISSUE THREAD

**Issue by slharris** [xray/xray#456] opened 2015-07-07 01:48 UTC
Is there a command to calculate percentiles?

I am currently using xray to create max, min and mean plots for each season for 40 years of data. I have tried replacing where I use 'max' with 'percentile' or 'quantile' and then change ('time') to ('time, 90) but there is no attribute 'percentile' or 'quantile'  

ds = xray.open_mfdataset('myfiles/*/*/*temp.nc')
mytemp=ds['temp']
eachseasonmax=mytemp.groupby('time.season').max('time')

Also is this the correct place for these types of questions?

Thanks

**Comment by shoyer** [comment] 2015-07-07 05:30
Yes, this is an appropriate place to ask these questions.

No, we don't have a percentile/quantile method currently. This would be a welcome addition if you are interested in putting together a pull request.

For now, you can work around it by using the reduce method: `ds.reduce(functools.partial(np.percentile, 95), dim='time')`

**Comment by shoyer** [comment] 2015-09-09 00:59
Closing as a dupe of https://github.com/xray/xray/issues/303

**Closed by shoyer** 2015-09-09 00:59 UTC
Labels: enhancement
